/** ===============================================
 * Author: Epsilon DSVA Team
 * 
 * NOTE: This test and all associated code and data
 * are confidential and are not to be shared with 
 * anyone outside of the Epsilon DSVA team.
 * 
 * 
 * ! ! ! Do Not Edit This File ! ! !
 =================================================*/

import express from "express";

const path = require("path");

const app = express();

// simulate delay
app.use((_req, _res, next) => setTimeout(() => next(), 1_000));

// serve public directory statically
app.use("/", express.static(path.join(__dirname, "public")));

export { app };
