/** ===============================================
 * Author: Epsilon DSVA Team
 * 
 * NOTE: This test and all associated code and data
 * are confidential and are not to be shared with 
 * anyone outside of the Epsilon DSVA team.
 * 
 * 
 * ! ! ! Do Not Edit This File ! ! !
 =================================================*/

import { app } from "./app";

// Add all Routes
import "./routes";

const { API_PORT = 3000 } = process.env;

app.listen(API_PORT, () => {
  console.log("server started at http://localhost:" + API_PORT);
});
